### PR TITLE
Get more of those Biolink categories in there

### PR DESCRIPTION
**Pull request by caufieldjh**

### CODE REVIEW

**Review by matentzn — COMMENTED** [review]
Don't merge this yet, I need to think about it for a moment.

**Comment by caufieldjh** [comment]
No worries - I don't even know if it works yet.

**Review by matentzn — APPROVED** [review]
Ok, maybe its fine.. Its not  100% safe - you should probably make an issue for a QC check to ensure that no class has more than 1 BL category - but i can think of a real life example where you would get something wrong.

**Comment by caufieldjh** [comment]
Yes, that's a good idea re: qc checks. I'll see what it looks like in KG form but I suspect some namespaces will now end up with >1 closely related BL cats, like:
```
    <!-- http://purl.obolibrary.org/obo/MP_0000001 -->

    <owl:NamedIndividual rdf:about="http://purl.obolibrary.org/obo/MP_0000001">
        <vocab:category rdf:resource="https://w3id.org/biolink/vocab/NamedThing"/>
        <vocab:category rdf:resource="https://w3id.org/biolink/vocab/OntologyClass"/>
        <vocab:category rdf:resource="https://w3id.org/biolink/vocab/PhenotypicFeature"/>
        <vocab:category rdf:resource="https://w3id.org/biolink/vocab/PhenotypicQuality"/>
    </owl:NamedIndividual>
```

**Pull request merged**
