### PR TITLE
Update repo for ODK changes; produce relation graph

### LINKED ISSUE #8: Use more stringent prefix filtering
Imported ontologies may contain any number of prefixes, including ones conflicting with other sources.
We should limit sources to expected ones to avoid downstream node conflicts.

### PR DESCRIPTION
**Pull request by caufieldjh**
- [x] Repository updates
- [ ] More stringent prefix filtering
- [x] Produce relation_graph output along with other artifacts

### CODE REVIEW

**Comment by caufieldjh** [comment]
The last item is really a non-issue: producing the RG output depends upon making `phenio.owl`, so the Makefile goal of `relation_graph` will produce both.

**Review by matentzn — COMMENTED** [review]
Was committing all these site files intentional?

**Comment by caufieldjh** [comment]
> Was committing all these site files intentional?

Nope, that should have gone on the gh-pages branch

**Comment by caufieldjh** [comment]
This is the set of all CURIE prefixes entering KG-Phenio (i.e., some, like HGNC prefixes, get processed further for normalization. These are the immediate result of transforming to KGX TSV):
```
APO
BFO
biolink
BSPO
BTO
CARO
CHEBI
CHR
CIO
CL
CLO
dcat
dcterms
dctypes
DDANAT
DOID
ECO
EMAPA
ENVO
faldo
FAO
FBbt
FBcv
FlyBase
FMA
foaf
FOODON
FYPO
GENO
GO
HP
IAO
MA
MF
MFOMD
MI
MONDO
MP
MPATH
NBO
NCBITaxon
NCIT
OBA
OBAN
OBI
OBO
OGMS
OIO
OMIM
Orphanet
owl
PATO
pav
PCO
PO
PR
PW
rdf
rdfs
RO
RXCUI
SEPIO
SIO
skos
SO
STATO
TO
UBERON
UMLS
UPHENO
WBBT
WBbt
WBPhenotype
XAO
XCO
ZFA
ZFS
ZP
```

In the following cases, the prefixes only exist as categories, likely from merging Biolink or retaining xrefs. They don't contribute any meaningful nodes to the eventual graph, or they only contribute one. Even so, they shouldn't be retained if they aren't serving a purpose in PHENIO.
```
APO
BTO
CARO
CHR
CIO
CLO
DDANAT
DOID
OMIM
RXCUI
TO
UMLS
pav
```
OMIM _definitely_ shouldn't be in there.

**Comment by caufieldjh** [comment]
Want to merge this PR so I can start new ones without this getting too stale - prefix filtering will go in new PR, while other repo updates will go in different PR(s)

**Pull request merged**
