### PR TITLE
Trim CARO, FAO, and STATO

### PR DESCRIPTION
**Pull request by caufieldjh**
By 'trim' I mean 'remove'.

### CODE REVIEW

**Comment by caufieldjh** [comment]
Strange, getting this error:
```bash
Component is different, updating.
robot --catalog catalog-v001.xml merge --input phenio-edit.owl  -i components/bfo.owl  -i components/fao.owl  -i components/emapa.owl  -i components/fbbt.owl  -i components/go.owl  -i components/hsapdv.owl  -i components/mondo.owl  -i components/mpath.owl  -i components/nbo.owl  -i components/ro.owl  -i components/uberon.owl  -i components/upheno.owl  -i components/wbbt.owl  -i components/zfa.owl  -i imports/merged_import.owl \
        --output tmp/phenio-full-unreasoned.owl
Could not load imported ontology: <http://purl.obolibrary.org/obo/phenio/components/emapa.owl> Cause: http://www.berkeleybop.org/ontologies/phenio/components/emapa.owl
Use the -vvv option to show the stack trace.
Use the --help option to see usage information.
make: *** [phenio.Makefile:22: tmp/phenio-full-unreasoned.owl] Error 1
```
which only seems strange because this *should* be a component. I'm guessing this is some `phenio-edit.owl` -related thing again

**Comment by caufieldjh** [comment]
The problem was that it (EMAPA) wasn't getting added to the catalog file for some reason

**Review by matentzn — APPROVED** [review]

**Comment by caufieldjh** [comment]
Ah, one underlying error is that source refresh isn't completing because the `uberon-bridge-to-nifstd` is missing (it 404's on https://raw.githubusercontent.com/obophenotype/uberon/master/src/ontology/bridge/uberon-bridge-to-nifstd.owl).

**Comment by caufieldjh** [comment]
That bridge got removed, so I'll remove it here, too.
See https://github.com/obophenotype/uberon/commit/ebdc7b157765c359769b9bfda645feb39460ca79

**Comment by caufieldjh** [comment]
Now I keep encountering this:
```
Mirror identical, ignoring.
if [ true  = true ] && [ true = true ]; then robot --catalog catalog-v001.xml merge  -i mirror/chebi.owl  -i mirror/eco.owl  -i mirror/ncbitaxon-taxslim.owl  -i mirror/oba.owl  -i mirror/pato.owl  -i mirror/uberon-bridge-to-emapa.owl  -i mirror/uberon-bridge-to-zfa.owl  -i mirror/uberon-bridge-to-ma.owl  -i mirror/uberon-bridge-to-wbbt.owl  -i mirror/uberon-bridge-to-fbbt.owl  -i mirror/uberon-bridge-to-fma.owl  -i mirror/cl-bridge-to-emapa.owl  -i mirror/cl-bridge-to-ma.owl  -i mirror/cl-bridge-to-fma.owl  -i mirror/cl-bridge-to-wbbt.owl  -i mirror/cl-bridge-to-fbbt.owl  -i mirror/cl-bridge-to-zfa.owl -o mirror/merged.owl; fi
make: *** No rule to make target 'imports/chebi_terms_combined.txt', needed by 'imports/chebi_import.owl'.  Stop.
Command exited with non-zero status 2
```

True, there's no rule to make `chebi_terms_combined.txt`, but there *is* one to make `$(IMPORTDIR)/%_terms_combined.txt` - this just doesn't appear to work for chebi?

**Comment by matentzn** [comment]
(note that goals sometimes fail like this "not exists" because one of their dependencies does not exist:

```
$(IMPORTDIR)/%_terms_combined.txt: $(IMPORTSEED) $(IMPORTDIR)/%_terms.txt
```

so check if $(IMPORTDIR)/%_terms.txt and $(IMPORTSEED) exist as files.

**Comment by caufieldjh** [comment]
True, the IMPORTSEED (tmp/seed.txt) didn't exist.
So I ran 
```
sh run.sh make tmp/seed.txt
```
and that seemed to work until it raised:
```
org.semanticweb.owlapi.model.UnloadableImportException: Could not load imported ontology: <http://purl.obolibrary.org/obo/phenio/imports/chebi_import.owl> Cause: /work/src/ontology/imports/chebi_import.owl (No such file or directory)
```
OK, that's fair, it doesn't exist there, so I did this:
```
sh run.sh make refresh-chebi
```
and the mirrors update, but then:
```
robot --catalog catalog-v001.xml convert --input phenio-edit.owl --format ofn --output tmp/phenio-preprocess.owl
org.semanticweb.owlapi.model.UnloadableImportException: Could not load imported ontology: <http://purl.obolibrary.org/obo/phenio/imports/chebi_import.owl> Cause: /work/src/ontology/imports/chebi_import.owl (No such file or directory)
```

**Comment by caufieldjh** [comment]
Even running `sh run.sh make imports/chebi_import.owl` alone produces that same error.

**Comment by caufieldjh** [comment]
The solution here was just to create placeholder `chebi_terms.txt` and `chebi_import.owl` in the `imports` directory, as they weren't getting created by other means.
I had to do the same for `eco`, and `pato` too.
and the `uberon-bridge-to-emapa`.
and `cl-bridge-to-emapa`.

**Pull request merged**
