### PR TITLE
Desperate attempt 1: using unmerge to get rid of offending axioms

### PR DESCRIPTION
**Pull request by matentzn**
Once we have this working, we should still try and fix upstream ontologies though!

### CODE REVIEW

**Comment by matentzn** [comment]
Note: PR is into your experimental branch.

**Comment by caufieldjh** [comment]
OK, should take care of that offending class relationship at least

**Comment by matentzn** [comment]
yes, you could use sparql DELETE as well, but my guess is there will be more.. :D

**Comment by caufieldjh** [comment]
I think multiple classes are contributing to the same issue. With `CARO_0000000 subClassOf BFO_0000040` unmerged, the unsatisfiables generally look like the following:

## [upper-lower axis](http://purl.obolibrary.org/obo/BSPO_0000011) SubClassOf [Nothing](http://www.w3.org/2002/07/owl#Nothing) ##

  - [upper-lower axis](http://purl.obolibrary.org/obo/BSPO_0000011) SubClassOf [anatomical axis](http://purl.obo
library.org/obo/BSPO_0000010)
    - [anatomical axis](http://purl.obolibrary.org/obo/BSPO_0000010) SubClassOf [anatomical line](http://purl.ob
olibrary.org/obo/UBERON_0006800)
      - [anatomical line](http://purl.obolibrary.org/obo/CARO_0000008) EquivalentTo [anatomical line](http://pur
l.obolibrary.org/obo/UBERON_0006800)
        - [anatomical line](http://purl.obolibrary.org/obo/CARO_0000008) SubClassOf [anatomical boundary](http:/
/purl.obolibrary.org/obo/CARO_0000010)
          - [anatomical boundary](http://purl.obolibrary.org/obo/CARO_0000010) SubClassOf [immaterial anatomical
 entity](http://purl.obolibrary.org/obo/CARO_0000007)
            - [immaterial anatomical entity](http://purl.obolibrary.org/obo/CARO_0000007) SubClassOf [anatomical
 entity](http://purl.obolibrary.org/obo/CARO_0000000)
              - [anatomical entity](http://purl.obolibrary.org/obo/CARO_0000000) EquivalentTo [anatomical entity
](http://purl.obolibrary.org/obo/UBERON_0001062)
                - [anatomical entity](http://purl.obolibrary.org/obo/UBERON_0001062) SubClassOf [material entity
](http://purl.obolibrary.org/obo/BFO_0000040)
            - [immaterial anatomical entity](http://purl.obolibrary.org/obo/CARO_0000007) SubClassOf [immaterial
 entity](http://purl.obolibrary.org/obo/BFO_0000141)
  - [material entity](http://purl.obolibrary.org/obo/BFO_0000040) DisjointWith [immaterial entity](http://purl.o
bolibrary.org/obo/BFO_0000141)

**Comment by matentzn** [comment]
This is wrong

[anatomical entity](http://purl.obolibrary.org/obo/UBERON_0001062) SubClassOf [material entity](http://purl.obolibrary.org/obo/BFO_0000040)

I removed it too.

**Comment by caufieldjh** [comment]
Great - looks like there's an unrelated CL vs. GO issue for BSPO too:

## [left side](http://purl.obolibrary.org/obo/BSPO_0000000) SubClassOf [Nothing](http://www.w3.org/2002/07/owl#Nothing) ##

  - [left side](http://purl.obolibrary.org/obo/BSPO_0000000) SubClassOf [left of](http://purl.obolibrary.org/obo/BSPO_0000110) some [right side](http://purl.obolibrary.org/obo/BSPO_0000007)
    - [right side](http://purl.obolibrary.org/obo/BSPO_0000007) SubClassOf [anatomical side](http://purl.obolibrary.org/obo/BSPO_0000054)
      - [anatomical side](http://purl.obolibrary.org/obo/BSPO_0000054) SubClassOf [anatomical region](http://purl.obolibrary.org/obo/BSPO_0000070)
        - [anatomical region](http://purl.obolibrary.org/obo/BSPO_0000070) SubClassOf [anatomical structure](http://purl.obolibrary.org/obo/UBERON_0000061)
          - [anatomical structure](http://purl.obolibrary.org/obo/UBERON_0000061) SubClassOf [end stage](http://purl.obolibrary.org/obo/RO_0002497) some [death stage](http://purl.obolibrary.org/obo/UBERON_0000071)
            - [death stage](http://purl.obolibrary.org/obo/UBERON_0000071) SubClassOf [part_of](http://purl.obolibrary.org/obo/BFO_0000050) some [life cycle](http://purl.obolibrary.org/obo/UBERON_0000104)
              - [life cycle](http://purl.obolibrary.org/obo/UBERON_0000104) SubClassOf [has_part](http://purl.obolibrary.org/obo/BFO_0000051) some [zygote stage](http://purl.obolibrary.org/obo/UBERON_0000106)
                - [zygote stage](http://purl.obolibrary.org/obo/UBERON_0000106) SubClassOf [part_of](http://purl.obolibrary.org/obo/BFO_0000050) some [embryo stage](http://purl.obolibrary.org/obo/UBERON_0000068)
                  - [embryo stage](http://purl.obolibrary.org/obo/UBERON_0000068) SubClassOf [precedes](http://purl.obolibrary.org/obo/BFO_0000063) some [fully formed stage](http://purl.obolibrary.org/obo/UBERON_0000066)
                    - [fully formed stage](http://purl.obolibrary.org/obo/UBERON_0000066) SubClassOf [preceded_by](http://purl.obolibrary.org/obo/BFO_0000062) some [organogenesis stage](http://purl.obolibrary.org/obo/UBERON_0000111)
                      - [organogenesis stage](http://purl.obolibrary.org/obo/UBERON_0000111) SubClassOf [preceded_by](http://purl.obolibrary.org/obo/BFO_0000062) some [neurula stage](http://purl.obolibrary.org/obo/UBERON_0000110)
                        - [neurula stage](http://purl.obolibrary.org/obo/UBERON_0000110) SubClassOf [part_of](http://purl.obolibrary.org/obo/BFO_0000050) some [neural tube formation](http://purl.obolibrary.org/obo/GO_0001841)
                          - [neural tube formation](http://purl.obolibrary.org/obo/GO_0001841) SubClassOf [results in formation of](http://purl.obolibrary.org/obo/RO_0002297) some [neural tube](http://purl.obolibrary.org/obo/UBERON_0001049)
                            - [neural tube](http://purl.obolibrary.org/obo/UBERON_0001049) SubClassOf [embryonic tissue](http://purl.obolibrary.org/obo/UBERON_0005291)
                              - [embryonic tissue](http://purl.obolibrary.org/obo/UBERON_0005291) SubClassOf [tissue](http://purl.obolibrary.org/obo/CARO_0000043)
                                - [tissue](http://purl.obolibrary.org/obo/CARO_0000043) SubClassOf [has_part](http://purl.obolibrary.org/obo/BFO_0000051) some [extracellular matrix](http://purl.obolibrary.org/obo/GO_0031012)
                                  - [extracellular matrix](http://purl.obolibrary.org/obo/GO_0031012) SubClassOf [external encapsulating structure](http://purl.obolibrary.org/obo/GO_0030312)
                                    - [external encapsulating structure](http://purl.obolibrary.org/obo/GO_0030312) SubClassOf [part_of](http://purl.obolibrary.org/obo/BFO_0000050) some [cell](http://purl.obolibrary.org/obo/CL_0000000)
                                  - [extracellular matrix](http://purl.obolibrary.org/obo/GO_0031012) SubClassOf [part_of](http://purl.obolibrary.org/obo/BFO_0000050) some [extracellular region](http://purl.obolibrary.org/obo/GO_0005576)
  - [part_of](http://purl.obolibrary.org/obo/BFO_0000050) some [cell](http://purl.obolibrary.org/obo/CL_0000000) DisjointWith [part_of](http://purl.obolibrary.org/obo/BFO_0000050) some [extracellular region](http://purl.obolibrary.org/obo/GO_0005576)

**Comment by shawntanzk** [comment]
I think "[extracellular matrix](http://purl.obolibrary.org/obo/GO_0031012) SubClassOf [external encapsulating structure](http://purl.obolibrary.org/obo/GO_0030312)" might be the issue here

I think external encapsulating structure should be part of cell cause of the comment (Comment
The outer membrane (of gram negative bacteria) or cell wall (of yeast or Gram positive bacteria) are defined as parts of this structure, see 'external encapsulating structure part'.) However, if it is part of the cell, by definition, it cannot be extracellular. I see that there needs to be a relation to it, but subclass might not be right - I'm thinking somewhere in the overlaps type of relation?

**Comment by matentzn** [comment]
@shawntanzk Thank you very much for your input. :) This helps a lot, we will ask you again when the issue is elevated to GO.

**Comment by balhoff** [comment]
Where does this axiom come from?

[extracellular matrix](http://purl.obolibrary.org/obo/GO_0031012) SubClassOf [part_of](http://purl.obolibrary.org/obo/BFO_0000050) some [extracellular region](http://purl.obolibrary.org/obo/GO_0005576)

It's not in GO.

**Comment by matentzn** [comment]
@balhoff says we should remove [extracellular matrix](http://purl.obolibrary.org/obo/GO_0031012) SubClassOf [part_of](http://purl.obolibrary.org/obo/BFO_0000050) some [extracellular region](http://purl.obolibrary.org/obo/GO_0005576)

**Comment by matentzn** [comment]
to do this:

1. find which ontology contains it
2. open in protege
3. save as ttl
4. find the axiom
5. paste in config/unmerge.ttl

**Comment by caufieldjh** [comment]
Thanks @matentzn , @shawntanzk , and @balhoff

**Comment by caufieldjh** [comment]
For reference, this is from upheno:
```
    <!-- http://purl.obolibrary.org/obo/GO_0031012 -->

    <owl:Class rdf:about="http://purl.obolibrary.org/obo/GO_0031012">
        <rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/GO_0030312"/>
        <rdfs:subClassOf>
            <owl:Restriction>
                <owl:onProperty rdf:resource="http://purl.obolibrary.org/obo/BFO_0000050"/>
                <owl:someValuesFrom rdf:resource="http://purl.obolibrary.org/obo/GO_0005576"/>
            </owl:Restriction>
        </rdfs:subClassOf>
        <obo:IAO_0000115>A structure lying external to one or more cells, which provides structural support, biochemical or biomechanical cues for cells or tissues.</obo:IAO_0000115>
        <oboInOwl:hasAlternativeId>GO:0005578</oboInOwl:hasAlternativeId>
        <oboInOwl:hasDbXref>NIF_Subcellular:nlx_subcell_20090513</oboInOwl:hasDbXref>
        <oboInOwl:hasDbXref>Wikipedia:Extracellular_matrix</oboInOwl:hasDbXref>
        <oboInOwl:hasExactSynonym>proteinaceous extracellular matrix</oboInOwl:hasExactSynonym>
        <oboInOwl:hasNarrowSynonym>matrisome</oboInOwl:hasNarrowSynonym>
        <oboInOwl:hasOBONamespace>cellular_component</oboInOwl:hasOBONamespace>
        <oboInOwl:id>GO:0031012</oboInOwl:id>
        <oboInOwl:inSubset rdf:resource="http://purl.obolibrary.org/obo/go#goslim_chembl"/>
        <oboInOwl:inSubset rdf:resource="http://purl.obolibrary.org/obo/go#goslim_drosophila"/>
        <oboInOwl:inSubset rdf:resource="http://purl.obolibrary.org/obo/go#goslim_generic"/>
        <oboInOwl:inSubset rdf:resource="http://purl.obolibrary.org/obo/go#goslim_pir"/>
        <oboInOwl:inSubset rdf:resource="http://purl.obolibrary.org/obo/go#prokaryote_subset"/>
        <rdfs:label>extracellular matrix</rdfs:label>
    </owl:Class>
```

**Comment by caufieldjh** [comment]
OK, that takes care of [extracellular matrix](http://purl.obolibrary.org/obo/GO_0031012) SubClassOf [part_of](http://purl.obolibrary.org/obo/BFO_0000050) some [extracellular region](http://purl.obolibrary.org/obo/GO_0005576) - we're down to 17965 unsatisfiable classes (vs. >200K before).

The current unsatisfiables generally resemble this:
                                                                                                                                                                                       
## [cyclodiene organochlorine insecticide](http://purl.obolibrary.org/obo/CHEBI_23457) SubClassOf [Nothing](http://www.w3.org/2002/07/owl#Nothing) ##

  - [cyclodiene organochlorine insecticide](http://purl.obolibrary.org/obo/CHEBI_23457) SubClassOf [organochlorine insecticide](http://purl.obolibrary.org/obo/CHEBI_25705)
    - [organochlorine insecticide](http://purl.obolibrary.org/obo/CHEBI_25705) SubClassOf [has role](http://purl.obolibrary.org/obo/RO_0000087) some [insecticide](http://purl.obolibrary.org/obo/CHEBI_24852)
      - [insecticide](http://purl.obolibrary.org/obo/CHEBI_24852) SubClassOf [molecular entity](http://purl.obolibrary.org/obo/CHEBI_23367)
        - [molecular entity](http://purl.obolibrary.org/obo/CHEBI_23367) SubClassOf [material entity](http://purl.obolibrary.org/obo/BFO_0000040)
          - [material entity](http://purl.obolibrary.org/obo/BFO_0000040) SubClassOf [independent continuant](http://purl.obolibrary.org/obo/BFO_0000004)
      - [insecticide](http://purl.obolibrary.org/obo/CHEBI_24852) SubClassOf [pesticide](http://purl.obolibrary.org/obo/CHEBI_25944)
        - [pesticide](http://purl.obolibrary.org/obo/CHEBI_25944) SubClassOf [application](http://purl.obolibrary.org/obo/CHEBI_33232)
          - [application](http://purl.obolibrary.org/obo/CHEBI_33232) SubClassOf [role](http://purl.obolibrary.org/obo/BFO_0000023)
            - [role](http://purl.obolibrary.org/obo/BFO_0000023) EquivalentTo [role](http://purl.obolibrary.org/obo/CHEBI_50906)
              - [role](http://purl.obolibrary.org/obo/CHEBI_50906) SubClassOf [realizable entity](http://purl.obolibrary.org/obo/BFO_0000017)
                - [realizable entity](http://purl.obolibrary.org/obo/BFO_0000017) SubClassOf [specifically dependent continuant](http://purl.obolibrary.org/obo/BFO_0000020)
  - [independent continuant](http://purl.obolibrary.org/obo/BFO_0000004) DisjointWith [specifically dependent continuant](http://purl.obolibrary.org/obo/BFO_0000020)

or the related conflict:

## [transfer RNA](http://purl.obolibrary.org/obo/CHEBI_17843) SubClassOf [Nothing](http://www.w3.org/2002/07/owl#Nothing) ##

  - [transfer RNA](http://purl.obolibrary.org/obo/CHEBI_17843) EquivalentTo [tRNA](http://purl.obolibrary.org/obo/SO_0000253)
    - [tRNA](http://purl.obolibrary.org/obo/SO_0000253) SubClassOf [derives_from](http://purl.obolibrary.org/obo/so#derives_from) some [tRNA_primary_transcript](http://purl.obolibrary.org/obo/SO_0000210)
      - [tRNA_primary_transcript](http://purl.obolibrary.org/obo/SO_0000210) SubClassOf [nc_primary_transcript](http://purl.obolibrary.org/obo/SO_0000483)
        - [nc_primary_transcript](http://purl.obolibrary.org/obo/SO_0000483) SubClassOf [primary_transcript](http://purl.obolibrary.org/obo/SO_0000185)
          - [primary_transcript](http://purl.obolibrary.org/obo/SO_0000185) SubClassOf [transcript](http://purl.obolibrary.org/obo/SO_0000673)
            - [transcript](http://purl.obolibrary.org/obo/SO_0000673) SubClassOf [ribonucleic acid](http://purl.obolibrary.org/obo/CHEBI_33697)
              - [ribonucleic acid](http://purl.obolibrary.org/obo/CHEBI_33697) SubClassOf [nucleic acid](http://purl.obolibrary.org/obo/CHEBI_33696)
                - [nucleic acid](http://purl.obolibrary.org/obo/CHEBI_33696) SubClassOf [macromolecule](http://purl.obolibrary.org/obo/CHEBI_33839)
                  - [macromolecule](http://purl.obolibrary.org/obo/CHEBI_33839) SubClassOf [molecular entity](http://purl.obolibrary.org/obo/CHEBI_23367)
                    - [molecular entity](http://purl.obolibrary.org/obo/CHEBI_23367) SubClassOf [material entity](http://purl.obolibrary.org/obo/BFO_0000040)
                      - [material entity](http://purl.obolibrary.org/obo/BFO_0000040) SubClassOf [independent continuant](http://purl.obolibrary.org/obo/BFO_0000004)
            - [transcript](http://purl.obolibrary.org/obo/SO_0000673) SubClassOf [gene_member_region](http://purl.obolibrary.org/obo/SO_0000831)
              - [gene_member_region](http://purl.obolibrary.org/obo/SO_0000831) SubClassOf [biological_region](http://purl.obolibrary.org/obo/SO_0001411)
                - [biological_region](http://purl.obolibrary.org/obo/SO_0001411) SubClassOf [region](http://purl.obolibrary.org/obo/SO_0000001)
                  - [region](http://purl.obolibrary.org/obo/SO_0000001) SubClassOf [generically dependent continuant](http://purl.obolibrary.org/obo/BFO_0000031)
  - [independent continuant](http://purl.obolibrary.org/obo/BFO_0000004) DisjointWith [generically dependent continuant](http://purl.obolibrary.org/obo/BFO_0000031)

I'm suspicious of [role](http://purl.obolibrary.org/obo/CHEBI_50906) SubClassOf [realizable entity](http://purl.obolibrary.org/obo/BFO_0000017) since I don't think that's in CHEBI but it's in upheno.owl.

**Comment by matentzn** [comment]
Lets stop the hunt here, I will find a way to provide uPheno as a base version. This is very non-trivial due to the idiosyncratic pipeline, but I think debugging all these axioms will take 100 years.

**Comment by caufieldjh** [comment]
OK - perhaps that will be a better solution in the long term anyway.

**Comment by caufieldjh** [comment]
Hey @matentzn, can we close this PR?

**Comment by matentzn** [comment]
100% if this is no longer a problem..

**Pull request closed without merging**
