### PR TITLE
Create and include minimal PHENIO build in artifacts

### LINKED ISSUE #58: Produce minimal version for test fixtures
Make an additional one-off build artifact, analogous to the `go-nucleus` used as a test fixture in libraries like `semsimian` (see https://github.com/monarch-initiative/semsimian/blob/main/tests/data/go-nucleus.db)
Because this should generally be static it should not require rebuilding with each release.

### PR DESCRIPTION
**Pull request by caufieldjh**

### CODE REVIEW

**Comment by matentzn** [comment]
What use case is driving this?

**Comment by caufieldjh** [comment]
> What use case is driving this?

Testing in semsimian and Monarch app. 
https://github.com/monarch-initiative/semsimian/issues/118

**Comment by caufieldjh** [comment]
The goal is to produce an artifact covering multiple phenotypes (i.e., ontology A + UPHENO + ontology B),
while also retaining other axioms present in PHENIO.
Would also like it to be <50 Mb and ideally more like 10 Mb (if that's even possible).
SLME/BOT with a single UPHENO term makes a really big extract here - hundreds of Mb.
SLME/STAR with a specific termset makes an extract of ~200 Mb. Still too big.
The subset method seems like it should work but still demands a whole lot of memory to complete since it calls relation-graph (and we already do that for the full ontology, so this feels kind of redundant + unnecessary).

**Comment by caufieldjh** [comment]
Ah, a MIREOT extract works well.

**Pull request merged**
