### PR TITLE
Refreshing repository to replace LFS-stored files

### PR DESCRIPTION
**Pull request by caufieldjh**
In some cases, files are too big to store here, so will go elsewhere once a semi-permanent location is identified.

### CODE REVIEW

**Comment by caufieldjh** [comment]
Repository is still `over its data quota`

**Comment by matentzn** [comment]
How can the ODK worflow run at all w/o imports and components checked in?

**Comment by caufieldjh** [comment]
Right now, it won't - `upheno` is 419 MB and `mondo` is >200 MB, so GH refuses to push them to the repo

**Comment by caufieldjh** [comment]
And unfortunately the only apparent solution to freeing up space from LFS is to...delete and re-create the repository.
Stand by...

**Pull request merged**
